---
- name: Set volume keybinds
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ dconf_settings }}"
  vars:
    dconf_settings:
      volume-down: "['<Super>minus']"
      volume-up: "['<Super>equal']"
      volume-mute: "['<Super>BackSpace']"

# use 'man xkeyboard-config' for options
- name: Set caps lock as escape modifier
  dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['caps:escape_shifted_capslock']"
