---
- name: Check if Kitty is installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/kitty.app/bin/kitty"
  register: kitty_present

- name: install kitty using binary installer
  block:
    - name: fetch binary installer from remote
      ansible.builtin.get_url:
        url: "https://sw.kovidgoyal.net/kitty/installer.sh"
        dest: "/tmp/kitty-installer.sh"
        mode: 0744

    - name: run the installer
      shell: "/tmp/kitty-installer.sh"

  when: ( kitty_present is not defined ) or ( not kitty_present.stat.exists | bool )
