---
  - name: check out the pyenv repo
    ansible.builtin.git:
      repo: https://github.com/pyenv/pyenv.git
      dest: "{{ ansible_env.HOME }}/.pyenv"

  - name: check out the virtualenv plugin for pyenv
    ansible.builtin.git:
      repo: https://github.com/pyenv/pyenv-virtualenv.git
      dest: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"

  - name: install pipx
    ansible.builtin.pip:
      name: pipx
      extra_args: --user

  - name: ensure pipx path (even in venvs)
    shell: "python3 -m pipx ensurepath"
