---
- name: make sure original config.fish file is gone
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
    state: absent

- name: run stow shell script
  shell: 
    cmd: "./stow.sh"
    chdir: "{{ ansible_env.HOME }}/env"

