---
- name: Check if neovim is installed
  ansible.builtin.stat:
    path: /usr/bin/nvim
  when: not force_update
  register: neovim_present

- name: Download and Install neovim
  block:
    - name: download neovim
      ansible.builtin.get_url:
        url: "https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb"
        dest: "/tmp/nvim-linux64.deb"
        mode: 0644

    - name: install neovim
      become: true
      ansible.builtin.apt: 
        deb: "/tmp/nvim-linux64.deb"
        state: present
  when: ( neovim_present.stat is not defined ) or ( not neovim_present.stat.exists | bool )
