---
- hosts: all
  vars:
    username: ubuntu
    env_git_branch: master

  tasks:
    - import_tasks: tasks/apt.yml
    - import_tasks: tasks/shell.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/kitty.yml
    - import_tasks: tasks/git.yml
